<?php

/**
 * PluginrtGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtGuardUserTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtGuardUser');
    }
}