<?php

/**
 * PlugingnSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugingnSiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugingnSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugingnSite');
    }
}