<?php

/**
 * PluginrtCategoryToObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtCategoryToObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtCategoryToObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtCategoryToObject');
    }
}