<?php

/**
 * PluginrtCommentReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtCommentReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtCommentReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtCommentReport');
    }
}