<?php

/**
 * PlugingnAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7264 2010-03-01 21:58:09Z jwage $
 */
abstract class PlugingnAsset extends BasegnAsset
{
  public function isImage()
  {
    $ext = gnAssetToolkit::getExtension($this->getOriginalFilename());

    if(in_array($ext, sfConfig::get('app_gn_web_image_extensions', array('gif','jpg','png'))))
    {
      return true;
    }
    return false;
  }
}