<?php

/**
 * PlugingnGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugingnGuardUserTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugingnGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugingnGuardUser');
    }
}