<?php

/**
 * PluginrtSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtSiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtSite');
    }
}