<?php

/**
 * PluginrtAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7264 2010-03-01 21:58:09Z jwage $
 */
abstract class PluginrtAsset extends BasertAsset
{
  /**
   * Is this asset an web image.
   *
   * @return boolean
   */
  public function isImage()
  {
    $ext = rtAssetToolkit::getExtension($this->getOriginalFilename());

    if(in_array($ext, sfConfig::get('app_rt_web_image_extensions', array('gif','jpg','png'))))
    {
      return true;
    }
    return false;
  }

  public function getSystemPath()
  {
    return sfConfig::get('sf_upload_dir') . DIRECTORY_SEPARATOR . $this->getFilename();
  }

  public function getWebPath()
  {
    $full_path = sfConfig::get('sf_upload_dir') . $this->getSubContainer() . DIRECTORY_SEPARATOR . $this->getFilename();

    return str_replace(sfConfig::get('sf_web_dir'), '', $full_path);
  }

  public function getSubContainer()
  {
    $sub_container = '';

    if($this->getProtected())
    {
      $sub_container = sfConfig::get('app_rt_asset_protected_dir', 'protected');
    }
    else
    {
      $sub_container = sfConfig::get('app_rt_asset_public_dir', '');
    }

    if($sub_container === '' || is_null($sub_container))
    {
      return '';
    }

    return DIRECTORY_SEPARATOR . $sub_container;
  }
}