<?php $admin_cred = sfConfig::get('app_gn_user_admin_credential', 'admin_user') . "\n" ?>

<?php if(sfConfig::get('app_gn_registration_is_private', false)): ?>

all:
  is_secure: true

<?php else: ?>

all:
  is_secure: false

<?php endif; ?>

confirm:
  is_secure: true
  credentials: <?php echo $admin_cred ?>