<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addrtsnippetversion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('rt_snippet_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             'site_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'collection' =>
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'published' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'published_from' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'published_to' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'version' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'version',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('rt_snippet_version');
    }
}