<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Removephonefromguarduser extends Doctrine_Migration_Base
{
  public function up() {
    $this->removeColumn('sf_guard_user', 'phone');
    $this->removeColumn('sf_guard_user', 'mobile');
    $this->removeColumn('sf_guard_user', 'fax');
  }

  public function down() {
    $this->addColumn('sf_guard_user', 'phone', 'string', '20', array());
    $this->addColumn('sf_guard_user', 'mobile', 'string', '20', array());
    $this->addColumn('sf_guard_user', 'fax', 'string', '20', array());
  }
}