<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Createpaymentindex extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('rt_periodic_payment_customer', 'rt_periodic_payment_customer_user_id_sf_guard_user_id', array(
            'name' => 'rt_periodic_payment_customer_user_id_sf_guard_user_id',
            'local' => 'user_id',
            'foreign' => 'id',
            'foreignTable' => 'sf_guard_user',
    ));
    $this->createForeignKey('rt_periodic_payment_event', 'rcri', array(
            'name' => 'rcri',
            'local' => 'customer_id',
            'foreign' => 'id',
            'foreignTable' => 'rt_periodic_payment_customer',
    ));
    $this->createForeignKey('rt_periodic_payment_invoice', 'reri', array(
            'name' => 'reri',
            'local' => 'event_id',
            'foreign' => 'id',
            'foreignTable' => 'rt_periodic_payment_event',
    ));
    $this->addIndex('rt_periodic_payment_customer', 'rt_periodic_payment_customer_user_id', array(
            'fields' =>
            array(
                    0 => 'user_id',
            ),
    ));
    $this->addIndex('rt_periodic_payment_event', 'rt_periodic_payment_event_customer_id', array(
            'fields' =>
            array(
                    0 => 'customer_id',
            ),
    ));
    $this->addIndex('rt_periodic_payment_invoice', 'rt_periodic_payment_invoice_event_id', array(
            'fields' =>
            array(
                    0 => 'event_id',
            ),
    ));
  }

  public function down()
  {
    $this->dropForeignKey('rt_periodic_payment_customer', 'rt_periodic_payment_customer_user_id_sf_guard_user_id');
    $this->dropForeignKey('rt_periodic_payment_event', 'rcri');
    $this->dropForeignKey('rt_periodic_payment_invoice', 'reri');
    $this->removeIndex('rt_periodic_payment_customer', 'rt_periodic_payment_customer_user_id', array(
            'fields' =>
            array(
                    0 => 'user_id',
            ),
    ));
    $this->removeIndex('rt_periodic_payment_event', 'rt_periodic_payment_event_customer_id', array(
            'fields' =>
            array(
                    0 => 'customer_id',
            ),
    ));
    $this->removeIndex('rt_periodic_payment_invoice', 'rt_periodic_payment_invoice_event_id', array(
            'fields' =>
            array(
                    0 => 'event_id',
            ),
    ));
  }
}