<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Createpayment extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('rt_periodic_payment_customer', array(
            'id' =>
            array(
                    'type' => 'integer',
                    'length' => '8',
                    'autoincrement' => '1',
                    'primary' => '1',
            ),
            'user_id' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'reference' =>
            array(
                    'type' => 'string',
                    'length' => '255',
            ),
            'created_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            'updated_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            ), array(
            'primary' =>
            array(
                    0 => 'id',
            ),
    ));
    $this->createTable('rt_periodic_payment_event', array(
            'id' =>
            array(
                    'type' => 'integer',
                    'length' => '8',
                    'autoincrement' => '1',
                    'primary' => '1',
            ),
            'reference' =>
            array(
                    'type' => 'string',
                    'length' => '255',
            ),
            'customer_id' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'card_number' =>
            array(
                    'type' => 'string',
                    'length' => '4',
            ),
            'card_type' =>
            array(
                    'type' => 'enum',
                    'notnull' => '1',
                    'values' =>
                    array(
                            0 => 'visa',
                            1 => 'mastercard',
                    ),
                    'length' => '',
            ),
            'card_expiry' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'amount' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'interval_value' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'interval_type' =>
            array(
                    'type' => 'enum',
                    'notnull' => '1',
                    'values' =>
                    array(
                            0 => 'days',
                            1 => 'months',
                            2 => 'years',
                    ),
                    'length' => '',
            ),
            'date_init' =>
            array(
                    'type' => 'date',
                    'length' => '25',
            ),
            'date_start' =>
            array(
                    'type' => 'date',
                    'length' => '25',
            ),
            'date_end' =>
            array(
                    'type' => 'date',
                    'length' => '25',
            ),
            'created_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            'updated_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            ), array(
            'primary' =>
            array(
                    0 => 'id',
            ),
    ));
    $this->createTable('rt_periodic_payment_invoice', array(
            'id' =>
            array(
                    'type' => 'integer',
                    'length' => '8',
                    'autoincrement' => '1',
                    'primary' => '1',
            ),
            'event_id' =>
            array(
                    'type' => 'integer',
                    'notnull' => '1',
                    'length' => '8',
            ),
            'status' =>
            array(
                    'type' => 'enum',
                    'notnull' => '1',
                    'values' =>
                    array(
                            0 => 'pending',
                            1 => 'failed',
                            2 => 'success',
                    ),
                    'length' => '',
            ),
            'reference' =>
            array(
                    'type' => 'string',
                    'length' => '20',
            ),
            'created_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            'updated_at' =>
            array(
                    'notnull' => '1',
                    'type' => 'timestamp',
                    'length' => '25',
            ),
            ), array(
            'primary' =>
            array(
                    0 => 'id',
            ),
    ));
  }

  public function down()
  {
    $this->dropTable('rt_periodic_payment_customer');
    $this->dropTable('rt_periodic_payment_event');
    $this->dropTable('rt_periodic_payment_invoice');
  }
}