<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('rt_comment', 'rt_comment_user_id_sf_guard_user_id', array(
             'name' => 'rt_comment_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('rt_comment', 'rt_comment_comment_id_rt_comment_id', array(
             'name' => 'rt_comment_comment_id_rt_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'rt_comment',
             ));
        $this->createForeignKey('rt_comment_report', 'rt_comment_report_comment_id_rt_comment_id', array(
             'name' => 'rt_comment_report_comment_id_rt_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'rt_comment',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('rt_comment', 'rt_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('rt_comment', 'rt_comment_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
        $this->addIndex('rt_comment_report', 'rt_comment_report_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('rt_comment', 'rt_comment_user_id_sf_guard_user_id');
        $this->dropForeignKey('rt_comment', 'rt_comment_comment_id_rt_comment_id');
        $this->dropForeignKey('rt_comment_report', 'rt_comment_report_comment_id_rt_comment_id');
        $this->removeIndex('rt_comment', 'rt_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('rt_comment', 'rt_comment_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
        $this->removeIndex('rt_comment_report', 'rt_comment_report_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }
}