<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
    $permission = new sfGuardPermission();
    $permission->setName('admin_comment');
    $permission->setDescription('Administration menu to be displayed');
    $permission->save();

    $group = Doctrine::getTable('sfGuardGroup')->findOneByName('admin');
    $group_permission = new sfGuardGroupPermission();
    $group_permission->setGroupId($group->getId());
    $group_permission->setPermissionId($permission->getId());
    $group_permission->save();
    
        $this->createTable('rt_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'model_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'model' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'comment_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'author_email' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'author_website' => 
             array(
              'type' => 'string',
              'extra' => 'link',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'moderator_note' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('rt_comment_report', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'reason' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'referer' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'valid',
              1 => 'invalid',
              2 => 'untreated',
              ),
              'default' => 'untreated',
              'length' => '',
             ),
             'comment_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        Doctrine::getTable('sfGuardPermission')->findByName('admin_menu_comment')->delete();
        $this->dropTable('rt_comment');
        $this->dropTable('rt_comment_report');
    }
}