rtIndex:

  columns:
    keyword:          string(100)
    model_id:         integer
    model:            string(100)
    site_id:          integer
    admin_only:       { type: boolean, default: 1 }
    published:        { type: boolean, default: 1 }
    published_from:   timestamp
    published_to:     timestamp

  indexes:
    keyword:
      fields:                [keyword]
    model:
      fields:                [model_id, model]

  relations:
    rtSite:
      local: site_id
      foreign: id
      onDelete: CASCADE

  attributes:
    export: [ all, constraints ] 